[syntax]
name = "C/C++"
extensions = ["c", "cc", "cpp", "cxx", "C", "h", "hh", "hpp", "hxx", "H", "ino"]

[tokens]
# Reserved words
'\<(alignas|alignof|and|and_eq|asm|auto|bitand|bitor|bool|break|case|catch|char|char8_t|char16_t|char32_t|class|compl|concept|const|consteval|constexpr|constinit|const_cast|continue|co_await|co_return|co_yield|decltype|default|delete|do|double|dynamic_cast|else|enum|explicit|export|extern|false|final|float|for|friend|goto|if|import|inline|int|long|module|mutable|namespace|new|noexcept|not|not_eq|nullptr|operator|or|or_eq|override|private|protected|public|register|reinterpret_cast|requires|return|short|signed|sizeof|static|static_assert|static_cast|struct|switch|template|this|thread_local|throw|true|try|typedef|typeid|typename|union|unsigned|using|virtual|void|volatile|wchar_t|while|xor|xor_eq)\>' = "red"

# Preprocessor reserved words
'^\s*#\s*(define|elif|else|endif|error|if|ifdef|ifndef|include|line|pragma|undef)' = "bright-red"

# Binary/Hex numbers
'\b0b[01]+\b' = "magenta"
'\b0x[0-9A-Fa-f]+\b' = "magenta"

# Numbers
'\b[+-]?\d+(\.\d+)?([eE][+-]?\d+)?\b' = "blue"

# Constants
'\b[A-Z_][A-Z0-9_]+\b' = "yellow"

# Strings
'"([^"\\]|(\\.))*"' = "green"

# Comments
'//.*$' = "gray"
'/\*[\s\S]*?\*/' = "gray"
