# Syntax configuration for Clojure files.
#
# Regular expressions must conform to the syntax supported by regex-lite.
# https://docs.rs/regex-lite/latest/regex_lite/index.html

[syntax]
name = "Clojure"
files = ['\.clj[s|c]?$', '\.edn$']

[tokens]
# Common functions
'\b(?:abs|and|apply|assoc|case|catch|comp|concat|condp?|conj|cons|constantly|count|dec|defn?|dissoc|distinct|do(?:all|run|seq|sync)?|drop(?:-while)?|eval|filter|finally|first|flatten|fn|get|identity|if(?:-(?:let|not))?|import|inc|interleave|into|keys|let(?:fn)?|loop|map|max|merge(?:-with)?|min|mod|not|ns|nth|or|partial|partition|print(?:ln)?|quot|quote|reduce|recur|rem|remainder|remove|require|rest|second|sort|str|subs|take(?:-while)?|throw|try|update(?:-in)?|use|vals|when(?:-(?:let|not))?)\b' = "orchid-bloom"

# Common functions whose regex needs alternate word boundaries
'\b(?:(contains|map|nil|seq|vector)[?])\B' = "orchid-bloom"
'\B\:else\b' = "orchid-bloom"
'\B[+\-/*=<>]\B' = "orchid-bloom"

# Common shorthand symbols
"[#']" = "verdant-spring"

# Common values
'\b(?:true|false|nil)\b' = "copper-flame"

# Parens and blocks
'[()]' = "deep-sapphire"
'[\[\]]' = "deep-sapphire"

# Strings
'"([^"\\]|\\.)*?"' = "peachy-orange"

# Comments
';.*$' = "sage-green"
