[syntax]
name = "HTML"
files = ['\.html?$']

[tokens]
# Tags
'<[A-Za-z\-:]+[A-Za-z0-9\-:]*?(?:\s|>)' = "orchid-bloom"
'</[A-Za-z\-:]+[A-Za-z0-9\-:]*?>' = "orchid-bloom"

# Strings
'"(?:[^"\\]|\\.)*"' = "peachy-orange"

# Comments
'<!--[\s\S]*?-->' = "sage-green"
