[syntax]
name = "Makefile"
files = ['[Mm]akefile$', '\.mk$']

[tokens]
# Reserved words
'\b(?:ifdef|ifndef|ifeq|ifneq|else|endif|define|endef|export|include|override|vpath)\b' = "red"

# Built-in functoins
'\b(?:subst|patsubst|wildcard|shell|addsuffix|addprefix|filter|filter-out)\b' = "blue"

# Built-in variables
'\$[@<^?*+|]' = "magenta"

# Operators
'[=,%]' = "magenta"
'\+=|\?=|:=|&&|\|\|' = "magenta"

# Strings
'"(?:[^"\\\n]|\\(?:.|\n))*"' = "green"
"'(?:[^'\\\\\\n]|\\\\(?:.|\\n))*'" = "green"

# Comments
'#.*$' = "gray"
