# Syntax configuration for Makefiles.
#
# Regular expressions must conform to the syntax supported by regex-lite.
# https://docs.rs/regex-lite/latest/regex_lite/index.html

[syntax]
name = "Makefile"
files = ['[Mm]akefile$', '\.mk$']

[tokens]
# Reserved words
'\b(?:ifdef|ifndef|ifeq|ifneq|else|endif|define|endef|export|include|override|vpath)\b' = "orchid-bloom"

# Built-in functions
'\b(?:subst|patsubst|wildcard|shell|addsuffix|addprefix|filter|filter-out)\b' = "crystal-cyan"

# Built-in variables
'\$[@<^?*+|]' = "misty-aqua"

# Operators
'[=,%]' = "lavender-haze"
'\+=|\?=|:=|&&|\|\|' = "lavender-haze"

# Strings
'"(?:\\(?:.|\n)|[^"\\\n])*"' = "peachy-orange"
"'(?:\\\\(?:.|\\n)|[^'\\\\\\n])*'" = "peachy-orange"

# Comments
'#.*$' = "sage-green"
