[syntax]
name = "Markdown"
files = ['\.md$', '\.markdown$', '\.mk(dn?)?$']

[tokens]
# Headers
'^#{1,6}.*' = "blue"

# Emphasis
'(?:^|[[:space:]])(?:_[^ ][^_]*_|\*[^ ][^*]*\*)' = "red"

# Emphasis (strong)
'(?:^|[[:space:]])(?:__[^ ][^_]*__|\*\*[^ ][^*]*\*\*)' = "red"

# code
'```.*$' = "magenta"
'`[^`\n]*`' = "magenta"

# links
'\[.*?\]\(.*?\)' = "green"
