[syntax]
name = "Markdown"
files = ['\.md$', '\.markdown$', '\.mk(dn?)?$']

[tokens]
# Headers
'^#{1,6}.*' = "twilight-blue"

# Emphasis
'(?:^|[[:space:]])(?:_[^ ][^_]*_|\*[^ ][^*]*\*)' = "orchid-bloom"

# Emphasis (strong)
'(?:^|[[:space:]])(?:__[^ ][^_]*__|\*\*[^ ][^*]*\*\*)' = "orchid-bloom"

# code
'```.*$' = "misty-aqua"
'`[^`\n]*`' = "misty-aqua"

# links
'\[.*?\]\(.*?\)' = "peachy-orange"
