[syntax]
name = "Markdown"
extensions = ["md"]

[tokens]
# Headers
'^#{1,6}.*' = [4, 232]

# Emphasis
'(^|[[:space:]])(_[^ ][^_]*_|\*[^ ][^*]*\*)' = [1, 232]

# Emphasis (strong)
'(^|[[:space:]])(__[^ ][^_]*__|\*\*[^ ][^*]*\*\*)' = [1, 232]

# code
'```.*$' = [5, 232]
'`([^`\n]*)`' = [5, 232]

# links
'\[(.*?)\]\((.*?)\)' = [2, 232]
