# Syntax configuration for Markdown files.
#
# Regular expressions must conform to the syntax supported by regex-lite.
# https://docs.rs/regex-lite/latest/regex_lite/index.html

[syntax]
name = "Markdown"
files = ['\.md$', '\.markdown$', '\.mk(dn?)?$']

[tokens]
# Headers
'^#{1,6}[ \t].*' = "twilight-blue"

# Horizontal line
'^(?:-{3,}|\*{3,}|_{3,})\s*$' = "slate-frost"

# Emphasis (strong)
'\*\*[^ \t\n][^*\n]*\*\*' = "verdant-spring"
'\b__[^ \t\n][^_\n]*__\b' = "verdant-spring"

# Emphasis
'\*[^ \t\n][^*\n]*\*' = "orchid-bloom"
'\b_[^ \t\n][^_\n]*_\b' = "orchid-bloom"

# Strikethrough
'(?:^|[ \t])~~[^ \t\n][^~\n]*~~' = "sage-green"

# Blockquotes
'^[ \t]*(?:>[ \t]+)+' = "copper-flame"

# Ordered lists
'^[ \t]*\d+\.[ \t]' = "burnt-orange"

# Unordered lists
'^[ \t]*-[ \t]' = "burnt-orange"

# Code
'```.*$' = "misty-aqua"
'`[^`\n]*`' = "misty-aqua"

# Links
'\[.*?\]\(.*?\)' = "peachy-orange"
