# Syntax configuration for ped help files.
#
# Regular expressions must conform to the syntax supported by regex-lite.
# https://docs.rs/regex-lite/latest/regex_lite/index.html

[syntax]
name = "Help"
files = ['^@(help|keys|operations|bindings|colors)$']

[tokens]
# Headers
'\[[^\[\]\n]+\]' = "twilight-blue"

# Copyright
'^Copyright.*$' = "verdant-spring"

# Links
'\bhttps://.*/ped\b' = "peachy-orange"
