[syntax]
name = "Properties"
files = ['\.properties$']

[tokens]
# Keys
'[^#!\s][^:=\s]*\s*[:=]' = "crystal-cyan"

# Unicode characters
'\\u[0-9A-Fa-f]{4}' = "verdant-spring"

# Comments
'[#!].*$' = "sage-green"
