[syntax]
name = "Ruby"
files = ['\.rb$']

[tokens]
# Reserved words
'\b(?:BEGIN|END|alias|and|begin|break|case|class|def|defined\?|do|else|elsif|end|ensure|false|for|if|in|module|next|nil|not|or|redo|rescue|retry|return|self|super|then|true|undef|unless|until|when|while|yield)\b' = "red"

# Numbers
'\b[+-]?\d+(?:\.\d+)?(?:[eE][+-]?\d+)?\b' = "blue"

# Strings
'"(?:[^"\\]|\\[\s\S])*"' = "green"
"'(?:[^'\\\\]|\\\\[\\s\\S])*'" = "green"

# Comments
'#[^{].*$' = "gray"
'##[^{].*$' = "gray"
