[syntax]
name = "Rust"
extensions = ["rs"]

[tokens]
# Reserved words
'\<(abstract|as|async|await|become|box|break|const|continue|crate|do|dyn|else|enum|extern|false|final|fn|for|if|impl|in|let|loop|macro|match|mod|move|mut|override|priv|pub|ref|return|self|static|struct|super|trait|true|try|type|typeof|unsafe|unsized|use|virtual|where|while|yield)\>' = "red"

# Numbers
'\<[+-]?\d+(\.\d+)?([eE][+-]?\d+)?\>' = "blue"

# Constants
'[A-Z][A-Z_]+' = "yellow"

# Macros
'[a-z_]+!' = "magenta"

# Attributes
'#!?\[.*?\]' = "blue"

# Strings
'"([^"\\]|(\\.))*"' = "green"
'r#+".*"#+' = "green"

# Comments
'//.*$' = "gray"
'/\*[\s\S]*?\*/' = "gray"
