[syntax]
name = "TOML"
files = ['\.toml$', '\.?pedrc$']

[tokens]
# Reserved words
'\b(?:false|true)\b' = "orchid-bloom"

# Numbers
'\b[+-]?\d+(?:\.\d+)?(?:[eE][+-]?\d+)?\b' = "verdant-spring"

# Headers
'^\s*\[[[:word:]-\.]+\]' = "misty-aqua"

# Bare keys
'^\s*[[:word:]-\.]+' = "golden-glow"

# Multi-line basic string
'"""[\s\S]*?"""' = "peachy-orange"

# Basic string
'"(?:[^"\\\n]|\\(?:.|\n))*"' = "peachy-orange"

# Multi-line literal string
"'''[\\s\\S]*?'''" = "peachy-orange"

# Literal string
"'[^'\\n]*'" = "peachy-orange"

# Comments
'#.*$' = "sage-green"
