# Syntax configuration for TOML files.
#
# Regular expressions must conform to the syntax supported by regex-lite.
# https://docs.rs/regex-lite/latest/regex_lite/index.html

[syntax]
name = "TOML"
files = ['\.toml$', '\.?pedrc$']

[tokens]
# Reserved words
'\b(?:false|true)\b' = "orchid-bloom"

# Numbers
'\b[+-]?\d+(?:\.\d+)?(?:[eE][+-]?\d+)?\b' = "verdant-spring"

# Headers
'^[ \t]*\[[\w.-]+\]' = "misty-aqua"

# Bare keys
'^[ \t]*[\w.-]+' = "golden-glow"

# Multi-line basic string
'"""[\s\S]*?"""' = "peachy-orange"

# Basic string
'"(?:\\(?:.|\n)|[^"\\\n])*"' = "peachy-orange"

# Multi-line literal string
"'''[\\s\\S]*?'''" = "peachy-orange"

# Literal string
"'[^'\\n]*'" = "peachy-orange"

# Comments
'#.*$' = "sage-green"
