[syntax]
name = "TOML"
extensions = ["toml"]

[tokens]
# Reserved words
'\<(false|true)\>' = "red"

# Numbers
'\<[+-]?\d+(\.\d+)?([eE][+-]?\d+)?\>' = "blue"

# Headers
'^\s*\[[[:word:]-\.]+\]' = "blue"

# Bare keys
'^\s*[[:word:]-\.]+' = "magenta"

# Multi-line basic string
'"""[\s\S]*?"""' = "green"

# Basic string
'"([^"\\]*(\\.[^"\\]*)*)"' = "green"

# Multi-line literal string
"'''[\\s\\S]*?'''" = "green"

# Literal string
"'[^'\\n]*'" = "green"

# Comments
'#.*$' = "gray"
