[syntax]
name = "TOML"
files = ['\.toml$', '\.?pedrc$']

[tokens]
# Reserved words
'\b(false|true)\b' = "red"

# Numbers
'\b[+-]?\d+(\.\d+)?([eE][+-]?\d+)?\b' = "blue"

# Headers
'^\s*\[[[:word:]-\.]+\]' = "blue"

# Bare keys
'^\s*[[:word:]-\.]+' = "magenta"

# Multi-line basic string
'"""[\s\S]*?"""' = "green"

# Basic string
'"([^"\\]*(\\.[^"\\]*)*)"' = "green"

# Multi-line literal string
"'''[\\s\\S]*?'''" = "green"

# Literal string
"'[^'\\n]*'" = "green"

# Comments
'#.*$' = "gray"
