# Syntax configuration for TypeScript files.
#
# Regular expressions must conform to the syntax supported by regex-lite.
# https://docs.rs/regex-lite/latest/regex_lite/index.html

[syntax]
name = "TypeScript"
files = ['\.ts$']

[tokens]
# Reserved words
'\b(?:abstract|as|asserts|async|await|boolean|break|byte|case|catch|class|const|continue|debugger|declare|default|delete|do|else|enum|export|extends|false|finally|final|for|from|function|get|goto|if|in|implements|import|instanceof|interface|int|in|is|infer|let|module|namespace|new|null|of|package|private|protected|public|readonly|return|static|set|super|switch|this|throw|true|try|typeof|type|undefined|var|void|while|with|yield)\b' = "orchid-bloom"

# Subset of operators
'=>' = "misty-aqua"

# Types
'\b(?:[A-Z][a-z]*)+\b' = "deep-sapphire"

# Decimal numbers
'\b[+-]?\d+(?:\.\d+)?(?:[eE][+-]?\d+)?\b' = "verdant-spring"

# Hex/Octal/Binary numbers
'\b0[xX][\dA-Fa-f]+\b' = "verdant-spring"
'\b0[oO][0-7]+\b' = "verdant-spring"
'\b0[bB][01]+\b' = "verdant-spring"

# Normal strings
'"(?:\\.|[^"\\\n])*"' = "peachy-orange"
"'(?:\\\\.|[^'\\\\\\n])*'" = "peachy-orange"

# Template literal strings
'`(?:\\.|[^`\\])*`' = "seafoam-mist"

# Comments
'//.*$' = "sage-green"
'/\*[\s\S]*?\*/' = "sage-green"
