# Syntax configuration for YAML files.
#
# Regular expressions must conform to the syntax supported by regex-lite.
# https://docs.rs/regex-lite/latest/regex_lite/index.html

[syntax]
name = "YAML"
files = ['\.ya?ml$']

[tokens]
# Special values
'\b(?:true|false|True|False|yes|no|Yes|No|on|off|On|Off|null|Null|NULL|~)\b' = "orchid-bloom"

# Type annotations
'!!(?:binary|bool|float|int|map|null|seq|set|str|timestamp)\b' = "verdant-spring"

# Keys
'^ *(?:- )?[A-Za-z_]+[\w.-]*?\s*:' = "crystal-cyan"

# Lists
'^ *- ' = "crystal-cyan"

# Block scalars
'(?:\||>)$' = "lavender-haze"

# Demarcation
'^(?:---|\.\.\.)' = "slate-frost"

# Double-quoted scalars
'"(?:\\.|[^"\\])*"' = "peachy-orange"

# Single-quoted scalars
"'(?:[^']|'')*'" = "peachy-orange"

# Comments
'#.*$' = "sage-green"
